import pandas as pd
df=pd.read_csv("Student_Performance_DT - Student_Performance_DT.csv")
print(df.head(5))
print(df.isna().sum())
print(df.duplicated())
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
df['Internet_Access']=le.fit_transform(df['Internet_Access'])
print(le.classes_)
le1= LabelEncoder()
df['Extracurricular'] = le1.fit_transform(df['Extracurricular'])
print(le1.classes_)
print(df.head())
X=df.drop("Final_Result",axis=1)
print(X.shape)
Y=df['Final_Result']
print(Y.shape)
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.20,random_state=42)
print(X_train.shape)
print(X_test.shape)
print(Y_train.shape)
print(Y_test.shape)
from sklearn.preprocessing import MinMaxScaler
scaler=MinMaxScaler()
scaler.fit(X_train)
print("Min value:", scaler.data_min_)
print("Max value:", scaler.data_max_)
print(X_train.min())
print(X_train.max())
X_train=scaler.transform(X_train)
print(X_train)
X_test=scaler.transform(X_test)
print(X_test)
from sklearn.tree import DecisionTreeClassifier
model=DecisionTreeClassifier(random_state=42)
model.fit(X_train,Y_train)
Y_pred=model.predict(X_test)
print(Y_pred)
